#!/usr/bin/env bash
# Regenerate src/ui/font_inter.h from Inter 4.1. Needs curl, unzip, pyftsubset
# (pip install fonttools) and xxd. The output is committed; normal builds do
# not run this script.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
URL=https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip
ZIP_SHA=9883fdd4a49d4fb66bd8177ba6625ef9a64aa45899767dde3d36aa425756b11e
CODEPOINTS="U+0020-007E,U+00D7,U+2212,U+2013,U+00B7,U+00E9,U+2026,U+2713"

curl -sSL -o "$WORK/inter.zip" "$URL"
echo "$ZIP_SHA  $WORK/inter.zip" | shasum -a 256 -c -
unzip -q "$WORK/inter.zip" extras/ttf/Inter-Regular.ttf extras/ttf/Inter-SemiBold.ttf LICENSE.txt -d "$WORK"
cp "$WORK/LICENSE.txt" "$ROOT/fonts/Inter-LICENSE.txt"

OUT="$ROOT/src/ui/font_inter.h"
{
    echo "/* Generated by tools/embed_font.sh from Inter 4.1 (SIL OFL 1.1, see"
    echo " * fonts/Inter-LICENSE.txt). Subset: $CODEPOINTS. Do not edit. */"
    echo "#ifndef FONT_INTER_H"
    echo "#define FONT_INTER_H"
    for W in Regular SemiBold; do
        pyftsubset "$WORK/extras/ttf/Inter-$W.ttf" --unicodes="$CODEPOINTS" \
            --layout-features='kern' --no-hinting --output-file="$WORK/inter_$W.ttf"
        LOWER=$(echo "$W" | tr '[:upper:]' '[:lower:]')
        (cd "$WORK" && xxd -i -n "k_inter_${LOWER}_ttf" "inter_$W.ttf") \
            | sed 's/^unsigned char/static const unsigned char/; s/^unsigned int/static const unsigned int/'
    done
    echo "#endif // FONT_INTER_H"
} > "$OUT"
echo "wrote $OUT"
